version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: emastercard_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /opt/emastercard/db_eight:/var/lib/mysql
    ports:
      - "3305:3306"
  api:
    build: .
    image: emastercard_api
    container_name: emastercard_api
    volumes:
      - ./api/api-config.yml:/opt/BHT-EMR-API/config/database.yml
      - ./api/migration-config.yml:/opt/eMastercard2Nart/config.yaml
      - ./tmp:/opt/eMastercard2Nart/tmp
    ports:
      - "9000:3000"
    depends_on:
      - mysqldb
    environment:
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
    links:
      - mysqldb:mysqldb
  
  dde4:
    build:
      context: ./
      dockerfile: Dockerfile.dde
    container_name: dde4
    volumes:
      - ./dde/dde_database.yml:/opt/dde4/config/database.yml
      - ./tmp/Demographics-Data-Exchange/schedule.yml:/opt/dde4/config/schedule.yml
      - ./tmp/Demographics-Data-Exchange/sidekiq.yml.example:/opt/dde4/config/sidekiq.yml

    ports:
      - "8005:8050"
    depends_on:
      - mysqldb
      - redis
      - sidekiq
    environment:
      RAILS_ENV: production
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1

  web:
    image: nginx
    container_name: emastercard_nginx
    volumes:
      - ./web/static:/opt/emastercard
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"

  redis:
    image: redis:latest
    build:
      context: .
      dockerfile: Dockerfile.dde
    container_name: dde_redis
    command: ["redis-server", "--bind", "127.0.0.1"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  
  sidekiq:
    image: sidekiq
    build:
      context: .
      dockerfile: Dockerfile.dde
    container_name: sidekiq
    command: bundle exec sidekiq
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://localhost:6379/0
      RAILS_ENV: production

volumes:
  redis-data:


