version: '3'
 
services:
 
  mysqldb:
    image: mysql:8.0
    container_name: emastercard_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /opt/emastercard/db_eight:/var/lib/mysql
    ports:
      - "3305:3306"
 
  api:
    image: emastercard_api
    container_name: emastercard_api
    volumes:
      - ./api/api-config.yml:/opt/BHT-EMR-API/config/database.yml
      - ./api/application.yml:/opt/BHT-EMR-API/config/application.yml
      - ./api/migration-config.yml:/opt/eMastercard2Nart/config.yaml
      - ./tmp:/opt/eMastercard2Nart/tmp
    ports:
      - "9000:3000"
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb
    environment:
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
  
  dde:
    image: emastercard_dde
    container_name: emastercard_dde
    volumes: 
      - ./dde/database.yml:/opt/dde4/config/database.yml
      - ./dde/application.yml:/opt/dde4/config/application.yml
      - ./dde/sidekiq.yml:/opt/dde4/config/sidekiq.yml
    ports:
      - "9001:8005"
    depends_on:
      - mysqldb
    links:
      - mysqldb:mysqldb
    environment:
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1

  redis:
    image: redis
    container_name: emastercard_redis
    ports:
      - "9002:6379"
 
  web:
    image: nginx
    container_name: emastercard_nginx
    volumes:
      - ./web/static:/opt/emastercard
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"