version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: emastercard_db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /opt/emastercard/db_eight:/var/lib/mysql
    ports:
      - "3305:3306"
  api:
    build: .
    image: emastercard_api
    container_name: emastercard_api
    volumes:
      - ./api/api-config.yml:/opt/BHT-EMR-API/config/database.yml
      - ./api/migration-config.yml:/opt/eMastercard2Nart/config.yaml
      - ./tmp:/opt/eMastercard2Nart/tmp
    ports:
      - "9000:3000"
    depends_on:
      - mysqldb
      - dde
    environment:
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
    links:
      - mysqldb:mysqldb
      - dde:dde
  
  dde:
    build:
      context: ./
      dockerfile: Dockerfile.dde
    container_name: emastercard_dde
    volumes:
      - ./dde/sidekiq.yml:/opt/dde4/config/sidekiq.yml
      - ./dde/database.yml:/opt/dde4/config/database.yml

    ports:
      - "8005:8050"
    depends_on:
      - mysqldb
      - redisdb
    environment:
      RAILS_ENV: production
      WEB_CONCURRENCY: 6
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
      REDIS_URL: redis://localhost:6379/0
    links:
      - mysqldb:mysqldb
      - redisdb:redisdb

  web:
    image: nginx
    container_name: emastercard_nginx
    volumes:
      - ./web/static:/opt/emastercard
      - ./web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"

  redisdb:
    image: redis
    container_name: emastercard_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:


